resolver: lts-16.22

packages:
- dapr-http-client
- dapr-http-server

allow-newer: true

extra-deps:
# mu
- mu-schema-0.3.0.0
- mu-rpc-0.4.0.1
- mu-optics-0.3.0.1
- mu-avro-0.4.0.2
- mu-protobuf-0.4.0.3
- mu-grpc-server-0.4.0.0
- mu-grpc-common-0.4.0.0
- compendium-client-0.2.1.1
# dependencies of mu
- http2-client-0.9.0.0
- http2-grpc-types-0.5.0.0
- http2-grpc-proto3-wire-0.1.0.0
- warp-grpc-0.4.0.1
- proto3-wire-1.4.0
- parameterized-0.5.0.0
- word-compat-0.0.5