resolver: lts-18.28

packages:
- dapr-http-client
- dapr-http-server
- dapr-grpc-client

allow-newer: true

extra-deps:
- mu-grpc-server-0.5.0.0
- mu-protobuf-0.4.2.0
- mu-rpc-0.5.0.2
- mu-schema-0.3.1.2
- compendium-client-0.2.1.1
- http2-grpc-proto3-wire-0.1.0.0
- http2-grpc-types-0.5.0.0
- mu-grpc-common-0.4.0.0
- warp-grpc-0.4.0.1
- mu-avro-0.4.0.4