name: Format check

on:
  push:
    branches: [ "master", "release-*" ]
  pull_request:
    branches: [ "master", "release-*" ]

  workflow_dispatch: {}

jobs:
  ormolu-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v7
      
